### ISSUE TITLE
E2 Custom Functions Not Working

### ISSUE THREAD

**Issue by VaporousCreeper** [bouletmarc/ACF_CustomMod#12]
Im getting "Expression 2 (ACD): entities/gmod_wire_expression2/core/custom/acfcustomfunctions.lua:21: attempt to index a nil value" when i start up my E2

it's the returning functions is braking it

**Comment by starwobble** [comment]
Seemed to be banned can i be unbanned vapourscreeprr

**Comment by starwobble** [comment]
eta on fix vaporouscreeper ?
