### ISSUE TITLE
Sound tool not working properly

### ISSUE THREAD

**Issue by nokillnando** [bouletmarc/ACF_CustomMod#6]
all engines,gearboxes,guns not made by ACF Custom tool aren't able to change sound.
the following error shows: acf_engine(acf_gearbox, acf_gun) is not supported by tool.

**Comment by bouletmarc** [comment]
the "ACF Sound Custom" should only be used on Custom ACF Entities, such as : 
-Acf engine maker entities
-Acf engine custom entities
-Acf turbocharger entities
-Acf supercharger entities

Use the original tool for original acf entities "ACF Sound"

**Comment by bouletmarc** [comment]
since this is not really an issue, I'll close it but I'll also take note that I can add all "sounding" acf entities through my custom sound tool in a futur update maybe ? making my tool a little more "universal".
