### ISSUE TITLE
Sound tool not working properly

### ISSUE THREAD

**Issue by nokillnando** [bouletmarc/ACF_CustomMod#7]
Sorry if i didnt say properly, I used the normal acf sound replacer tool. But just like I posted before it says acf_engine,gearbox,gun isn't supported by the tool.
It looks like its conflicting.

**Comment by bouletmarc** [comment]
the original sound replacer must be used on original acf entities, as I just said in the last post, their no issue, use "acf sound replacer custom" for custom acf entities, its tested and working.

If you get that error, its because you are using the wrong tool on the worng entites made for it.
