### ISSUE TITLE
Engine maker engines spawn as error when duped

### ISSUE THREAD

**Issue by Nwhis** [bouletmarc/ACF_CustomMod#8]
If I spawn an engine made in the engine maker and dupe it, the ghost shows up with the correct model. Upon spawning it, however, it shows up as an error, and the only way to remove the error is via admin cleanup (cleaning the entire map). Advanced duplicator 2 just spawns the error and nothing else happens, but advanced duplicator 1 gives this error in the console:

`AdvDupeERROR: CreateEntity failed to make "acf_engine_maker", Error: addons/acf_custommod-master/lua/entities/acf_engine_maker.lua:267: attempt to compare number with nil`
`stack traceback:`
    `addons/acf_custommod-master/lua/entities/acf_engine_maker.lua:267: in function <addons/acf_custommod-master/lua/entities/acf_engine_maker.lua:218>`
`[C]: in function 'xpcall'`
`workshop/lua/autorun/server/advdupe.lua:2570: in function 'CreateEntityFromTable'`
`workshop/lua/autorun/server/advdupe.lua:2416: in function 'PasteEntity'`
`workshop/lua/autorun/server/advdupe.lua:2009: in function 'Paste'`
`workshop/lua/autorun/server/advdupe.lua:1955: in function 'NormPaste'`
`workshop/lua/autorun/server/advdupe.lua:1925: in function <workshop/lua/autorun/server``/advdupe.lua:1924>`
`[C]: in function 'xpcall'`
`workshop/lua/autorun/server/advdupe.lua:1707: in function 'fn'`
`workshop/lua/ulib/shared/hook.lua:110: in function <workshop/lua/ulib/shared/hook.lua:93>`

This happens in singleplayer and on a multiplayer ACF build server.

**Comment by bouletmarc** [comment]
will be fixed in the next update, i'm throwing it in about no time, thank you for reporting this issue.

 I tought that I was cleaning 'unused' variables in the last update, but finally they were used for duplicator, I've just put them back and it's working.
